# config.
version: "3"

networks:
  prolegis-net:
    driver: bridge

# volumes.
volumes:
  prolegis-database-data:
  prolegis-redis-data:
  prolegis-dot-config:
  prolegis-dot-local:
  prolegis-dot-cache:
  prolegis-dot-composer:

# services.
services:
  # MySQL.
  db:
    image: mysql:8.0
    container_name: prolegis-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    tty: true
    networks:
      - prolegis-net
    volumes:
      - prolegis-database-data:/var/lib/mysql
      - './.docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
    ports:
      - 33307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=prolegisblit
      - MYSQL_DATABASE=prolegis
      - MYSQL_USER=prolegis
      - MYSQL_PASSWORD=prolegis

  api:
    build: ./.docker/php
    container_name: prolegis-app
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
    #   - './.docker/php/programs.conf:/etc/supervisor/conf.d/programs.conf'
    networks:
      - prolegis-net
    depends_on:
        - db
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  nginx:
    build: ./.docker/nginx
    container_name: prolegis-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/nginx.conf/:/etc/nginx/conf.d/default.conf
    networks:
      - prolegis-net
    depends_on:
      - api
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

#   supervisor:
#     build: ./.docker/supervisor
#     container_name: prolegis-supervisor
#     tty: true
#     restart: always
#     volumes:
#       - ./:/var/www
#       - './.docker/supervisor/programs.conf:/etc/supervisor/conf.d/programs.conf'
#     networks:
#       - prolegis-net
#     depends_on:
#       - api
#     extra_hosts:
#       - "host.docker.internal:172.17.0.1"

  redis:
    image: redis:6-alpine
    container_name: prolegis-redis
    command: redis-server --bind 0.0.0.0 --requirepass '@secret99D'
    restart: unless-stopped
    networks:
      - prolegis-net
    depends_on:
      - api
    volumes:
      - prolegis-redis-data:/data
    ports:
      - 6379
